/**
 * SBOM lockfile-coverage tests (v0.3.0 — m4_yarn_lock_sbom).
 *
 * Pins the yarn.lock coverage gap: before v0.3.0 sbom.ts derived lockfile SBOMs
 * for package-lock.json / pnpm-lock.yaml / requirements.txt but NOT yarn.lock,
 * so a yarn-based MCP server silently fell back to a file-manifest SBOM and its
 * real upstream deps were never named. These tests prove that a directory whose
 * only lockfile is yarn.lock (classic v1 OR berry YAML) now derives a
 * `source: "lockfile"` SBOM naming the declared packages.
 *
 * Fully local: just filesystem + the pure sbom functions, no network/signing.
 */

import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { promises as fs } from "node:fs";
import * as os from "node:os";
import * as path from "node:path";

import { buildFileManifest } from "../src/manifest.js";
import { deriveSbom, detectSbomStrategy, sbomFromLockfile } from "../src/sbom.js";

let tmp: string;

beforeEach(async () => {
  tmp = await fs.mkdtemp(path.join(os.tmpdir(), "attestload-sbom-"));
});

afterEach(async () => {
  await fs.rm(tmp, { recursive: true, force: true });
});

/** A minimal classic (Yarn v1) yarn.lock with one scoped + one plain dep. */
const CLASSIC_YARN_LOCK = `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


"@babel/code-frame@^7.0.0", "@babel/code-frame@^7.10.4":
  version "7.12.13"
  resolved "https://registry.yarnpkg.com/@babel/code-frame/-/code-frame-7.12.13.tgz#abc"
  integrity sha512-HV1Cm0Q3ZrpCR93tkWOYiuYIgLxZXZFVG2VgK+MBWjUqZTundupPCB5 ==

lodash@^4.17.21:
  version "4.17.21"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz#def"
  integrity sha512-v2kDEe57lecTulaDIuNTPy3Ry4gLGJ6Z1O3vE1krgXZNrsQ+LFTGHVxVjcXPs17LhbZVGedAJv8XZ1tvj5FvKw ==
`;

/** A minimal berry (Yarn v2+) yarn.lock (valid YAML, __metadata header). */
const BERRY_YARN_LOCK = `# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!

__metadata:
  version: 8
  cacheKey: 10c0

"lodash@npm:^4.17.21":
  version: 4.17.21
  resolution: "lodash@npm:4.17.21"
  checksum: 10c0/d8cbea072bb08655bb4c989da418994b073a608dffa608b09ac04b43a791b12ac1d
  languageName: node
  linkType: hard

"@babel/code-frame@npm:^7.10.4":
  version: 7.12.13
  resolution: "@babel/code-frame@npm:7.12.13"
  checksum: 10c0/aaaa
  languageName: node
  linkType: hard
`;

describe("yarn.lock SBOM derivation", () => {
  it("detectSbomStrategy picks yarn.lock for an mcp-server dir", async () => {
    await fs.writeFile(path.join(tmp, "yarn.lock"), CLASSIC_YARN_LOCK);
    const strat = await detectSbomStrategy(tmp, "mcp-server");
    expect(strat.source).toBe("lockfile");
    expect(strat.lockfile).toBe("yarn.lock");
  });

  it("derives a lockfile SBOM naming the declared packages (classic v1)", async () => {
    await fs.writeFile(path.join(tmp, "yarn.lock"), CLASSIC_YARN_LOCK);
    await fs.writeFile(path.join(tmp, "index.js"), "export const x = 1;\n");

    const files = await buildFileManifest(tmp);
    const { sbom, strategy } = await deriveSbom(tmp, "mcp-server", files);

    expect(strategy.source).toBe("lockfile");
    const names = sbom.packages.map((p) => p.name).sort();
    expect(names).toContain("@babel/code-frame");
    expect(names).toContain("lodash");

    const lodash = sbom.packages.find((p) => p.name === "lodash");
    expect(lodash?.version).toBe("4.17.21");
    // Every package carries a stable content-addressed digest handle.
    for (const p of sbom.packages) {
      expect(p.digest).toMatch(/^[0-9a-f]{64}$/);
    }
  });

  it("derives a lockfile SBOM from a berry (YAML) yarn.lock", async () => {
    await fs.writeFile(path.join(tmp, "yarn.lock"), BERRY_YARN_LOCK);
    await fs.writeFile(path.join(tmp, "index.js"), "export const x = 1;\n");

    const files = await buildFileManifest(tmp);
    const { sbom, strategy } = await deriveSbom(tmp, "mcp-server", files);

    expect(strategy.source).toBe("lockfile");
    const names = sbom.packages.map((p) => p.name).sort();
    // berry descriptors carry an `npm:` protocol — name must survive intact.
    expect(names).toContain("lodash");
    expect(names).toContain("@babel/code-frame");
    const lodash = sbom.packages.find((p) => p.name === "lodash");
    expect(lodash?.version).toBe("4.17.21");
  });

  it("a yarn-based mcp-server no longer silently falls back to file-manifest", async () => {
    await fs.writeFile(path.join(tmp, "yarn.lock"), CLASSIC_YARN_LOCK);
    await fs.writeFile(path.join(tmp, "server.js"), "export const y = 2;\n");

    const files = await buildFileManifest(tmp);
    const { sbom } = await deriveSbom(tmp, "mcp-server", files);
    // Regression guard: the SBOM source is the lockfile, and it names upstream
    // deps — NOT the dir's own files (which is what file-manifest would yield).
    expect(sbom.source).toBe("lockfile");
    expect(sbom.packages.some((p) => p.name === "server.js")).toBe(false);
    expect(sbom.packages.some((p) => p.name === "lodash")).toBe(true);
  });
});

// ---------------------------------------------------------------------------
// v0.12.0 fix — parseRequirements strips PEP 508 extras and stops the version
// at compound-specifier commas (no more "[security]==2.31.0" as a version).
// ---------------------------------------------------------------------------
describe("v0.12.0: requirements.txt SBOM strips extras + compound specifiers", () => {
  it("extras (name[extra]==version) do not leak into the version field", async () => {
    await fs.writeFile(
      path.join(tmp, "requirements.txt"),
      'requests[security]==2.31.0\nbcrypt>=3.2,<4.0; python_version >= "3.8"\nclick\n',
    );
    const sbom = await sbomFromLockfile(tmp, "requirements.txt");
    const req = sbom.packages.find((p) => p.name === "requests");
    expect(req).toBeDefined();
    expect(req!.version).toBe("2.31.0");
    expect(req!.version).not.toContain("[security]");
    expect(req!.version).not.toContain("==");
  });

  it("a compound specifier (>=3.2,<4.0) yields the first pinned version only", async () => {
    await fs.writeFile(
      path.join(tmp, "requirements.txt"),
      'bcrypt>=3.2,<4.0; python_version >= "3.8"\n',
    );
    const sbom = await sbomFromLockfile(tmp, "requirements.txt");
    const bc = sbom.packages.find((p) => p.name === "bcrypt");
    expect(bc).toBeDefined();
    expect(bc!.version).toBe("3.2");
    expect(bc!.version).not.toContain(",");
  });
});

// ---------------------------------------------------------------------------
// v0.12.0 fix — parsePackageLock names a nested transitive dep by its bare
// child name (foo), not the path-qualified "lodash/node_modules/foo".
// ---------------------------------------------------------------------------
describe("v0.12.0: package-lock.json nested package name", () => {
  it("a nested transitive (node_modules/a/node_modules/b) is named 'b'", async () => {
    const pkgLock = JSON.stringify(
      {
        name: "demo",
        version: "1.0.0",
        lockfileVersion: 3,
        packages: {
          "": { name: "demo", version: "1.0.0" },
          "node_modules/lodash": {
            version: "4.17.21",
            license: "MIT",
            integrity: "sha512-v2kDEe57lecTulaDIuNTPy3Ry4gLGJ6Z1O3vE1krgXZNrsQ+LFTGHVxVjcXPs17LhbZVGedAJv8XZ1tvj5FvKw==",
          },
          "node_modules/lodash/node_modules/foo": {
            version: "1.2.3",
            integrity: "sha512-aaa==",
          },
          "node_modules/@babel/code-frame": {
            version: "7.0.0",
            license: "MIT",
            integrity: "sha512-HV1Cm0Q3ZrpCR93tkWOYiuYIgLxZXZFVG2VgK+MBWjUqZTundupPCB5/g==",
          },
        },
      },
      null,
      2,
    );
    await fs.writeFile(path.join(tmp, "package-lock.json"), pkgLock);
    const sbom = await sbomFromLockfile(tmp, "package-lock.json");
    const foo = sbom.packages.find((p) => p.name === "foo");
    expect(foo).toBeDefined();
    expect(foo!.version).toBe("1.2.3");
    // No package carries a path-qualified node_modules/ name.
    expect(sbom.packages.some((p) => p.name.includes("node_modules/"))).toBe(false);
    // Top-level + scoped deps are still named correctly.
    expect(sbom.packages.some((p) => p.name === "lodash")).toBe(true);
    expect(sbom.packages.some((p) => p.name === "@babel/code-frame")).toBe(true);
  });
});
